# Generated by Django 3.0.8 on 2020-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.FilePathField(path='/img')),
                ('privileges_users', models.CharField(max_length=12)),
                ('privileges_projects', models.CharField(max_length=12)),
                ('privileges_devices', models.CharField(max_length=12)),
                ('privileges_experiments', models.CharField(max_length=12)),
                ('privileges_animals', models.CharField(max_length=12)),
                ('privileges_reports', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rol_id', models.IntegerField()),
                ('email', models.URLField()),
                ('password', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
