# Generated by Django 3.0.8 on 2020-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('breed', models.CharField(blank=True, max_length=200)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('weight', models.CharField(blank=True, max_length=6)),
                ('picture_url', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_id', models.IntegerField()),
            ],
        ),
    ]
