# Generated by Django 3.0.8 on 2020-08-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packetheat',
            old_name='humidty_percentage',
            new_name='humidity_percentage',
        ),
    ]
