# Generated by Django 3.0.8 on 2020-08-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0002_auto_20200807_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('experiment_id', models.IntegerField()),
                ('raw', models.CharField(default=' ', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property_1', models.CharField(default=' ', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='packetheat',
            name='humidity_percentage',
        ),
    ]
