# Generated by Django 3.0.8 on 2020-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0003_auto_20200807_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetheat',
            name='humidity_percentage',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
