# Generated by Django 3.0.8 on 2020-08-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0004_packetheat_humidity_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('experiment_id', models.IntegerField()),
                ('raw', models.CharField(default=' ', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(default=' ', max_length=12)),
                ('uid', models.CharField(default=' ', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
