# Generated by Django 3.0.8 on 2020-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0005_packetip'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetch4',
            name='ch4_adc',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
