# Generated by Django 3.0.8 on 2020-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_id', models.IntegerField(default=0)),
                ('experiment_id', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=600)),
                ('firmware', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=200)),
                ('picture_url', models.CharField(blank=True, max_length=2000)),
                ('last_signal_level', models.CharField(max_length=6)),
                ('last_battery_level', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
